    Import the numpy package under the name np

In [1]:
import numpy as np

    Create a null vector of size 10

In [2]:
null_vector = np.zeros(10)

In [4]:
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


    Create a vector with values ranging from 10 to 49

In [6]:
values_10to49 = np.arange(10,49)



    Find the shape of previous array in question 3



In [8]:
values_10to49.shape

(39,)



    Print the type of the previous array in question 3



In [9]:
type(values_10to49)

numpy.ndarray



    Print the numpy version and the configuration



In [ ]:
print(np.__version__)
print(np.show_config())



    Print the dimension of the array in question 3



In [10]:
values_10to49.ndim

1



    Create a boolean array with all the True values



In [16]:
a  = np.ones(10, dtype='bool')



    Create a two dimensional array



In [18]:
two_d = np.array([[1,2,3],[4,5,6]])



    Create a three dimensional array



In [20]:
three_d = np.array([[[1,2,3],[4,5,6]]])



    Reverse a vector (first element becomes last)



In [27]:
values_10to49[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])



    Create a null vector of size 10 but the fifth value which is 1



In [31]:
n_v = np.zeros(10, dtype='int8')
n_v[6] = 1



    Create a 3x3 identity matrix



In [34]:
identity_matrix = np.identity(3)


    arr = np.array([1, 2, 3, 4, 5])
    Convert the data type of the given array from int to float

In [41]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr.astype('float32')


    arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
    Multiply arr1 with arr2

In [42]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])



    arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

    Make an array by comparing both the arrays provided above


In [46]:
compare_arrays = arr1 == arr2



    Extract all odd numbers from arr with values(0-9)

`

In [47]:
arr[arr % 2 == 1]

array([1., 3., 5.], dtype=float32)



    Replace all odd numbers to -1 from previous array



In [49]:
arr[arr % 2 == 1] = -1



    arr = np.arange(10)

    Replace the values of indexes 5,6,7 and 8 to 12



In [59]:
arr = np.arange(10)
arr[5:9] =12

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])



    Create a 2d array with 1 on the border and 0 inside



In [65]:
x = np.ones((4,4))
x[1:3,1:3] = 0



    arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

    Replace the value 5 to 12


In [69]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[1,1] = 12



    arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

    Convert all the values of 1st array to 64


In [76]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,0] = 64



    Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it



In [85]:
arr2d0_9 = np.arange(10).reshape(2,5)
arr2d0_9[0,0]

0



    Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it



In [91]:
arr2d0_9 = np.arange(10).reshape(2,5)
arr2d0_9[1,1]

6



    Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows



In [99]:
arr2d0_9 = np.arange(10).reshape(2,5)
arr2d0_9[0:,4:]

array([[4],
       [9]])



    Create a 10x10 array with random values and find the minimum and maximum values



In [107]:
random_array = np.random.random((10,10))
ra_min = random_array.min()
ra_max = random_array.max()


    a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

    Find the common items between a and b


In [110]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])



    a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

    Find the positions where elements of a and b match


In [112]:
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)



    names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

    Find all the values from array data where the values from array names are not equal to Will


In [115]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)




    names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

    Find all the values from array data where the values from array names are not equal to Will and Joe




    Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.



In [120]:
array2d = np.arange(1,16).reshape(5,3)
array2d.astype('float32')

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]], dtype=float32)



    Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.



In [122]:
array3d = np.arange(1,17).reshape(2,2,4)
array3d.astype('float32')

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]], dtype=float32)



    Swap axes of the array you created in Question 32





    Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0



In [127]:
array_sq = np.arange(10)
array_sq ** 2
np.where(array_sq < 0.5 , 0, array_sq)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


      Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays


In [172]:
a = np.random.random(12)
b = np.random.random(12)

np.maximum(a,b)

array([0.2538877 , 0.38104623, 0.53283515, 0.83892204, 0.7684733 ,
       0.95842424, 0.82780169, 0.76850194, 0.6765635 , 0.69330058,
       0.81943799, 0.16751885])



    names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

Find the unique names and sort them out!


In [146]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.sort(np.unique(names))

array(['Bob', 'Joe', 'Will'], dtype='<U4')



    a = np.array([1,2,3,4,5]) b = np.array([5,6,7,8,9])

From array a remove all items present in array b


In [150]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

np.setdiff1d(a, b)

array([1, 2, 3, 4])



    Following is the input NumPy array delete column two and insert following new column in its place.

sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = numpy.array([[10,10,10]])


In [164]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])

sampleArray = np.delete(sampleArray, 1, axis = 1)
sampleArray = np.insert(sampleArray, 1, newColumn, axis = 1)



    x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])

Find the dot product of the above two matrix


In [166]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])

np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

Generate a matrix of 20 random values and find its cumulative sum

In [167]:
random_a = np.random.random(20)

np.sum(random_a)

12.796034340108925