# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [5]:
import numpy as np
array1to2d = np.arange(10)
print("1D array : ", array1to2d)
array1to2d = array1to2d.reshape(2,5)
array1to2d

1D array :  [0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [14]:
a1 = np.arange(10).reshape(2,5)
a2 = np.ones(10, dtype='int16').reshape(2,5)
np.vstack((a1,a2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [15]:
a1 = np.arange(10).reshape(2,5)
a2 = np.ones(10, dtype='int16').reshape(2,5)
np.hstack((a1,a2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [18]:
a1 = np.arange(10).reshape(2,5)
a1.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [24]:
a3 = np.arange(15).reshape(3,5,1)
a3.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [30]:
a4 = np.arange(15)
a4.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [43]:
a5 = np.arange(25).reshape(5,5)
a5**2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [51]:
a6 = np.arange(30).reshape(5,6)
a6.mean()

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [49]:
a6.std()

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [52]:
np.median(a6)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [56]:
np.transpose(a6)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [74]:
a7 = np.arange(1,17).reshape(4,4)
print(a7)
np.diagonal(a7)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([ 1,  6, 11, 16])

## Question:13

### Find the determinant of the previous array in Q12?

In [75]:
np.linalg.det(a7)

4.7331654313261276e-30

## Question:14

### Find the 5th and 95th percentile of an array?

In [79]:
a8 = np.array([[10, 7, 4], [3, 2, 1]])
print("5th percentile",np.percentile(a8,5))
print("95th percentile",np.percentile(a8,95))

5th percentile 1.25
95th percentile 9.25


## Question:15

### How to find if a given array has any null values?

In [91]:
a9 = np.array([1,2,3,4])
np.isnan(a9)

array([False, False, False, False])